REM ****************************************************************************
REM *  Generated by Microsoft Visual Studio
REM *  Copyright (c) Microsoft Corporation. All rights reserved.
REM *  
REM ****************************************************************************

set DeploymentDirectory=C:\GIT\Telerik\TESTRE~1\TH7421~1\Out
set TestRunDirectory=C:\GIT\Telerik\TESTRE~1\TH7421~1
set TestRunResultsDirectory=C:\GIT\Telerik\TESTRE~1\TH7421~1\In\SRI-TH~1
set TotalAgents=1
set AgentWeighting=100
set AgentLoadDistributor=Microsoft.VisualStudio.TestTools.Execution.AgentLoadDistributor
set AgentId=1
set TestDir=C:\GIT\Telerik\TESTRE~1\TH7421~1
set ResultsDirectory=C:\GIT\Telerik\TESTRE~1\TH7421~1\In
set DataCollectionEnvironmentContext=Microsoft.VisualStudio.TestTools.Execution.DataCollectionEnvironmentContext
set TestLogsDir=C:\GIT\Telerik\TESTRE~1\TH7421~1\In\SRI-TH~1
set ControllerName=localhost:6901
set TestDeploymentDir=C:\GIT\Telerik\TESTRE~1\TH7421~1\Out
set AgentName=SRI-THARINDA

REM ****************************************************************************
REM *  User Commands
REM *  
REM ****************************************************************************
@echo off

"C:\GIT\Telerik\CS\SupportingScripts\SendSummaryMail.py"

exit